//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StartingPoint.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class LookupCategory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LookupCategory()
        {
            this.LookupCategoryValues = new HashSet<LookupCategoryValue>();
        }
    
        public System.Guid LookupCategoryId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public System.DateTime Added { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LookupCategoryValue> LookupCategoryValues { get; set; }
    }
}
