//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StartingPoint.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        public System.Guid PersonId { get; set; }
        public Nullable<System.Guid> HouseholdId { get; set; }
        public Nullable<System.Guid> HouseholdRoleId { get; set; }
        public Nullable<System.Guid> MembershipStatusId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string PrimaryEmailAddress { get; set; }
        public string PrimaryPhoneNumber { get; set; }
        public string Address { get; set; }
        public string AddressCity { get; set; }
        public string AddressState { get; set; }
        public string AddressZip { get; set; }
        public Nullable<System.Guid> CampusId { get; set; }
        public System.DateTime Added { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
    
        public virtual Household Household { get; set; }
        public virtual LookupCategoryValue LookupCategoryValue { get; set; }
        public virtual LookupCategoryValue LookupCategoryValue1 { get; set; }
    }
}
